services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio
    volumes:
      - minio-data:/mnt/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    command: ["python", "run.py"]
    env_file:
      - .env.prod
    ports:
      - "127.0.0.1:5000:5000"
    restart: always
    hostname: web
    depends_on:
      - minio

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web


volumes:
  minio-data:
